spring.application.name=proyecto-ferreteria

spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto_ferreteria
spring.datasource.username=postgres
spring.datasource.password=ecuacion
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
